# SPDX-License-Identifier: GPL-3.0-or-later
# Anaconda configuration file for DefenestraOS

[Profile]
profile_id = defenestraos

[Profile Detection]
os_id = defenestraos

[Network]
default_on_boot = FIRST_WIRED_WITH_LINK

[Bootloader]
efi_dir = fedora
menu_auto_hide = True

[Storage]
default_scheme = BTRFS
btrfs_compression = zstd:1
default_partitioning =
    /     (min 1 GiB, max 70 GiB)
    /home (min 500 MiB, free 50 GiB)
    /var  (btrfs)

[User Interface]
custom_stylesheet = /usr/share/anaconda/pixmaps/fedora.css
hidden_spokes =
    NetworkSpoke
    PasswordSpoke
    UserSpoke

hidden_webui_pages =
    anaconda-screen-accounts
    anaconda-screen-date-time

[Localization]
use_geolocation = False
