# SPDX-License-Identifier: GPL-3.0-or-later
# DefenestraOS Live ISO builder
# Takes built DefenestraOS image, adds live session + Anaconda installer
# Run with --cap-add sys_admin --security-opt label=disable

ARG BASE_IMAGE=${BASE_IMAGE:-localhost/defenestraos:latest}
ARG INSTALL_IMAGE_PAYLOAD=${INSTALL_IMAGE_PAYLOAD:-localhost/defenestraos:latest}
ARG FLATPAK_DIR_SHORTNAME=${FLATPAK_DIR_SHORTNAME:-gnome_flatpaks}

FROM $BASE_IMAGE
ARG BASE_IMAGE
ARG INSTALL_IMAGE_PAYLOAD
ARG FLATPAK_DIR_SHORTNAME
RUN --mount=type=bind,source=./.,target=/src \
    env \
    BASE_IMAGE="$BASE_IMAGE" \
    INSTALL_IMAGE_PAYLOAD="$INSTALL_IMAGE_PAYLOAD" \
    FLATPAK_DIR_SHORTNAME="$FLATPAK_DIR_SHORTNAME" \
    /src/build.sh
